baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Camp Hopkins'
publishDir = '../dist'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [module.hugoVersion]
    extended = false
    min = "0.143.0"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[markup]
  [markup.highlight]
    style = 'catppuccin-latte'

