name: Deploy site to S3 via Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Add TF Deployment Creds
        run: |
          echo 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' >> $GITHUB_ENV
          echo 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' >> $GITHUB_ENV
          echo 'access_key="${{ secrets.AWS_ACCESS_KEY_ID }}"' >> tf/terraform.auto.tfvars
          echo 'secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"' >> tf/terraform.auto.tfvars

      - name: Terraform Initialize
        run: terraform -chdir=tf init

      - name: Terraform Plan
        run: terraform -chdir=tf plan

      - name: Terraform Apply
        run: terraform -chdir=tf apply -auto-approve

