name: Deploy site to S3 via Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Add TF Deployment Creds
        run: |
          echo 'access_key="${{ secrets.ACCESS_KEY }}"' >> tf/terraform.tfvars
          echo 'secret_key="${{ secrets.SECRET_KEY }}"' >> tf/terraform.tfvars
          echo 'aws_region="${{ secrets.AWS_REGION }}"' >> tf/terraform.tfvars
          echo 'domain_name="${{ secrets.DOMAIN_NAME }}"' >> tf/terraform.tfvars

      - name: Terraform Initialize
        run: terraform -chdir=tf init
        env:
          TF_VAR_secret_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_access_key: ${{ secrets.SECRET_KEY }}

      - name: Terraform Plan
        run: terraform -chdir=tf plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform -chdir=tf apply -auto-approve -var-file=terraform.tfvars

